name: Release

on: workflow_dispatch

jobs:
  release:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        package:
          - unexpected-realtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build

      - name: Pack
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
        run: |
          npm run pack

      - name: Publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
        run: |
          version="$(jq -r .version package.json)"

          echo "Publishing ${{ matrix.package }}@$version"
          npm run publish --access public

          echo "npm: \`+ ${{ matrix.package }}@$version\`" >> $GITHUB_STEP_SUMMARY
